proto:
	protoc --go_out=. --go_opt=module=github.com/btsomogyi/arbiter/example/examplepb --go-grpc_opt=module=github.com/btsomogyi/arbiter/example/examplepb --go-grpc_out=. examplepb.proto
.PHONY: proto